engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"
  duplication:
    enabled: true
    config:
      languages:
      - java
      - scala
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.scala"
  - "**.java"
exclude_paths:
- *.iml
- .idea/
- **/.project
- **/.settings
- **/.classpath
- **/.pydevproject
- **/.gitignore
- **/*.pyc
- **/*$py.class
- **/target/*
- **/dependency-reduced-pom.xml
- **/*.*~
- **.tar.gz
- **/_build/
- **.DS_Store
- **.versionsBackup
- checkpoints/
- logs/
- **/node_modules/*
- **/app/jspm_packages/*
- **/log/
